In [1]:
import numpy as np
import faiss

In [9]:
d = 3                          # dimension
nb = 4                      # database size
nq = 2                     # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.

xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

ids = np.arange(nb) * 10
print(ids)
print(xb)
print(xq)

[ 0 10 20 30]
[[0.19151945 0.62210876 0.43772775]
 [0.7863586  0.77997583 0.2725926 ]
 [0.27846426 0.8018722  0.95813936]
 [0.87893265 0.35781726 0.5009951 ]]
[[0.6834629  0.71270204 0.37025076]
 [0.5621962  0.50308317 0.01376845]]


In [11]:
# make faiss available
index = faiss.IndexFlatL2(d)   # build the index
index = faiss.IndexIDMap(index)
index.add_with_ids(xb, ids)          # add vectors to the index

In [12]:
k = 2                        # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
D, I = index.search(xq, k)     # actual search
print(I)    
print(D)

[[ 0 20]
 [10 30]
 [20  0]
 [30 10]]
[[0.         0.31070253]
 [0.         0.23895551]
 [0.         0.31070253]
 [0.         0.23895551]]
[[10 30]
 [10  0]]
[[0.0246504  0.18124568]
 [0.19390827 0.33130985]]
